---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sites/34a/f/f7d85e3f87/public_html
    - /bin/rm -rf $DEPLOYPATH/_next
    - /bin/cp -R web/out/* $DEPLOYPATH/
    - /bin/cp -R web/out/images $DEPLOYPATH/ 2>/dev/null; true
