---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sites/34a/f/f7d85e3f87/public_html
    - /bin/cp -f web/out/*.html $DEPLOYPATH/
    - /bin/cp -f web/out/robots.txt $DEPLOYPATH/
    - /bin/cp -f web/out/sitemap.xml $DEPLOYPATH/
    - /bin/cp -f web/out/favicon.ico $DEPLOYPATH/
    - /bin/cp -Rf web/out/_next $DEPLOYPATH/
    - /bin/cp -Rf web/out/images $DEPLOYPATH/
    - /bin/cp -f .htaccess $DEPLOYPATH/
